const Person = require('./person')
const Book = require('./book')
const Faker = require('faker')
bookName = () => Faker.random.words()
personName = () => Faker.name.firstName() + ' ' + Faker.name.lastName()
const Database = require('./database')

person_1 = new Person(personName())
person_2 = new Person(personName())


book_1 = new Book(bookName())
book_2 = new Book(bookName())
book_3 = new Book(bookName())

person_1.borrow(book_1)
person_2.lend(book_1)
person_2.borrow(book_2)
person_1.lend(book_2)
person_1.read(book_2)
//person_1.printActivities()
//person_2.printActivities()
//book_2.printStatistics()

Database.save(person_1, 'person1.json')
Database.save(person_2, 'person2.json')
Database.save(book_1, 'book1.json')
Database.save(book_2, 'book2.json')
Database.save(book_3, 'book3.json')
loadedFile = Database.load('book2.json')
console.log(loadedFile.title)